language: rust

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

os:
  - linux

script:
  - |
      cd wayland-sys &&
      travis-cargo test -- --features "dlopen egl client server cursor" &&
      cd ../scanner &&
      travis-cargo test &&
      cd ../wayland-client &&
      travis-cargo test -- --features "dlopen egl cursor all_stable_protocols" &&
      travis-cargo --only nightly test -- --features "dlopen egl cursor all_stable_protocols all_unstable_protocols" &&
      cd ../wayland-server &&
      travis-cargo test -- --features "dlopen" &&
      travis-cargo --only nightly test -- --features "dlopen unstable-protocols wpu-xdg_shell" &&
      cd .. &&
      travis-cargo --only nightly doc -- -p wayland-sys --no-deps &&
      travis-cargo --only nightly doc -- -p wayland-scanner --no-deps &&
      travis-cargo --only nightly doc -- -p wayland-client --no-deps &&
      travis-cargo --only nightly doc -- -p wayland-server --no-deps &&
      echo "Finished !"

after_success:
  - travis-cargo --only nightly doc-upload

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: A/zuPuIu03Z+rqnDS/NNNjbXrg8Nc9lEGKzcBdpHgnyd23z37zreEEAKzFhjJKMx0np0ntDo5LVeLgT6d7fGaDFsJrBZHej3pxuG81MAJdLEmJNaCLCc1eCbwDHgJkEJ5HsblHTrYK0RjBvNL5I8+URuzEqXkwVr7UHJv5px1ZA=
