language: rust

sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
  - which rustfmt || cargo install rustfmt
  - which mdbook || cargo install mdbook
  - which cargo-install-update || cargo install cargo-update
  - cargo install-update -a
  - pip install 'travis-cargo<0.2' --user
  - mkdir $(pwd)/socket
  - export XDG_RUNTIME_DIR="$(pwd)/socket"

os:
  - linux

script:
  - cargo fmt -- --all --write-mode=diff
  - |
      cd wayland-sys &&
      travis-cargo test -- --features "dlopen egl client server cursor" &&
      travis-cargo --only nightly doc -- --no-deps --features "dlopen egl client server cursor" &&
      cd ../wayland-scanner &&
      travis-cargo test &&
      travis-cargo --only nightly doc -- --no-deps &&
      cd ../wayland-client &&
      travis-cargo test -- --features "dlopen egl cursor" &&
      travis-cargo --only nightly doc -- --no-deps --features "dlopen egl cursor" &&
      cd ../wayland-server &&
      travis-cargo test -- --features "dlopen" &&
      travis-cargo --only nightly doc -- --no-deps --features "dlopen" &&
      cd ../wayland-protocols &&
      travis-cargo test -- --features "unstable_protocols client server wayland-client/dlopen wayland-server/dlopen" &&
      travis-cargo --only nigthly test -- features "unstable_protocols client server nightly wayland-client/dlopen wayland-server/dlopen" &&
      travis-cargo --only nightly doc -- --no-deps --features "unstable_protocols client server nightly wayland-client/dlopen wayland-server/dlopen" &&
      cd .. &&
      echo "Finished !"

after_success:
  - mdbook build
  - cp ./index.html ./rust.css ./target/doc/
  - ./doc_upload.py

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: A/zuPuIu03Z+rqnDS/NNNjbXrg8Nc9lEGKzcBdpHgnyd23z37zreEEAKzFhjJKMx0np0ntDo5LVeLgT6d7fGaDFsJrBZHej3pxuG81MAJdLEmJNaCLCc1eCbwDHgJkEJ5HsblHTrYK0RjBvNL5I8+URuzEqXkwVr7UHJv5px1ZA=

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxldmFucyUzQXNhZmFyYWRlZy5uZXQvJTIxRkt4aGprSUNwakJWelZlQ2RGJTNBc2FmYXJhZGVnLm5ldA"
        on_success: change
        on_failure: always
        on_start: never
