language: rust

sudo: required

cache: cargo

dist: trusty

addons:
  apt:
    packages:
      - libssl-dev

before_install:
  - sudo add-apt-repository -y ppa:wayland.admin/daily-builds
  - sudo apt-get update -qq
  - sudo apt-get install -y libwayland-dev

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - mkdir $(pwd)/socket
  - export XDG_RUNTIME_DIR="$(pwd)/socket"
  - |
      if [ $TRAVIS_RUST_VERSION = "nightly" ]; then
        which rustfmt || cargo install rustfmt-nightly -- --force
      fi
  - which cargo-tarpaulin || cargo install cargo-tarpaulin
  - which cargo-install-update || cargo install cargo-update
  - cargo install-update -a

os:
  - linux

script:
  - |
      if [ $TRAVIS_RUST_VERSION = "nightly" ]; then
        cargo fmt --all -- --write-mode=diff
      fi
  - cargo build --all --all-features
  - cargo test
  - cargo doc --all --no-deps --all-features

after_success:
  - ./doc_upload.py
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxldmFucyUzQXNhZmFyYWRlZy5uZXQvJTIxRkt4aGprSUNwakJWelZlQ2RGJTNBc2FmYXJhZGVnLm5ldA"
        on_success: change
        on_failure: always
        on_start: never
