language: rust

sudo: required

cache: cargo

dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_install:
  - sudo add-apt-repository -y ppa:wayland.admin/daily-builds
  - sudo apt-get update -qq
  - sudo apt-get install -y libwayland-dev

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
  - which rustfmt || cargo install rustfmt
  - which mdbook || cargo install mdbook
  - which cargo-coveralls || cargo install cargo-travis
  - which cargo-install-update || cargo install cargo-update
  - cargo install-update -a
  - pip install 'travis-cargo<0.2' --user
  - mkdir $(pwd)/socket
  - export XDG_RUNTIME_DIR="$(pwd)/socket"

os:
  - linux

script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build --all --all-features
  - cargo test
  - cargo doc --all --no-deps --all-features

after_success:
  - mdbook build
  - cp ./index.html ./rust.css ./target/doc/
  - ./doc_upload.py
  - cargo coveralls

env:
  global:
    - secure: A/zuPuIu03Z+rqnDS/NNNjbXrg8Nc9lEGKzcBdpHgnyd23z37zreEEAKzFhjJKMx0np0ntDo5LVeLgT6d7fGaDFsJrBZHej3pxuG81MAJdLEmJNaCLCc1eCbwDHgJkEJ5HsblHTrYK0RjBvNL5I8+URuzEqXkwVr7UHJv5px1ZA=

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxldmFucyUzQXNhZmFyYWRlZy5uZXQvJTIxRkt4aGprSUNwakJWelZlQ2RGJTNBc2FmYXJhZGVnLm5ldA"
        on_success: change
        on_failure: always
        on_start: never
