[package]
name = "wayland-test"
version = "0.0.1"
description = "Automating tests for other crates. Not to be published"

[dependencies]
wayland-sys = { path = "wayland-sys", features = ["dlopen", "client", "egl", "cursor", "server"] }
wayland-scanner = { path = "scanner" }
wayland-client = { path = "wayland-client", features = ["dlopen", "egl", "cursor"] }
wayland-server = { path = "wayland-server" }
