[package]
name = "wayland-client"
version = "0.1.7"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_client/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol."

[dependencies]
bitflags = "0.1"
libc = "0.1"
lazy_static = "0.1"

[dev-dependencies]
byteorder = "0.3"
