[package]
name = "wayland-client"
version = "0.0.1"
authors = ["Victor Berger <victor.berger@m4x.org>"]

[dependencies]
libc = "0.1"

[dev-dependencies]
byteorder = "0.3"
tempfile = "*"

[features]
all = ["wl_egl"]
wl_egl = []