[package]
name = "wayland-client"
version = "0.6.0-alpha"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_client/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol, client side."
build = "build.rs"

[dependencies]
bitflags = ">= 0.5.0, < 0.7"
crossbeam = "0.2"
libc = "0.2"
lazy_static = { version = ">= 0.1, < 0.3", optional = true }
wayland-sys = { version = "0.6.0-alpha", features = ["client"], path = "../wayland-sys" }

[build-dependencies]
wayland-scanner = { version = "0.6.0-alpha", path = "../scanner" }

[dev-dependencies]
byteorder = ">= 0.3, < 0.6"
tempfile = "2.1"

[features]
dlopen = ["wayland-sys/dlopen"]
egl = ["wayland-sys/egl"]
cursor = ["wayland-sys/cursor"]
wp-presentation_time = []
wp-viewporter = []
unstable-protocols = []
wpu-xdg_shell = []
all_stable_protocols=[
    "wp-presentation_time",
    "wp-viewporter"
]
all_unstable_protocols = [
    "unstable-protocols",
    "wpu-xdg_shell"
]