[package]
name = "wayland-client"
version = "0.6.0-alpha"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_client/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol."
build = "build.rs"

[dependencies]
bitflags = "0.3.3"
crossbeam = "0.1.5"
dlib = "0.2"
libc = "0.2"
lazy_static = { version = "0.1", optional = true }
wayland-sys = { version = "0.5.7", features = ["client"] }

[build-dependencies]
wayland-scanner = { version = "0.5.8" }

[dev-dependencies]
byteorder = "0.3"
tempfile = "1.1"

[features]
dlopen = ["dlib/dlopen", "wayland-sys/dlopen"]
egl = ["wayland-sys/egl"]
cursor = ["wayland-sys/cursor"]
