[package]
name = "wayland-protocols"
version = "0.9.3"
documentation = "https://vberger.github.io/wayland-rs/wayland_protocols/"
repository = "https://github.com/vberger/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
keywords = ["wayland", "client", "server", "protocol", "extension"]
description = "Generated API for the officials wayland protocol extensions"
build = "build.rs"
categories = ["gui", "api-bindings"]

[badges]
travis-ci = { repository = "vberger/wayland-rs" }

[dependencies]
wayland-sys = { version = "0.9.3", path = "../wayland-sys" }
wayland-client = { version = "0.9.3", path = "../wayland-client", optional = true }
wayland-server = { version = "0.9.3", path = "../wayland-server", optional = true }
bitflags = "0.7"

[build-dependencies]
wayland-scanner = { version = "0.9.3", path = "../wayland-scanner" }

[features]
client = ["wayland-client"]
server = ["wayland-server"]
nightly = []
unstable_protocols = []

