[package]
name = "wayland-protocols"
version = "0.7.5"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_protocols/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
keywords = ["wayland", "client", "server", "protocol", "extension"]
description = "Generated API for the officials wayland protocol extensions"
build = "build.rs"

[dependencies]
wayland-sys = { version = "0.7.5", path = "../wayland-sys" }
wayland-client = { version = "0.7.5", path = "../wayland-client", optional = true }
wayland-server = { version = "0.7.5", path = "../wayland-server", optional = true }
bitflags = "0.7"

[build-dependencies]
wayland-scanner = { version = "0.7.5", path = "../wayland-scanner" }

[features]
client = ["wayland-client"]
server = ["wayland-server"]
nightly = []
unstable_protocols = []

