[package]
name = "wayland-egl"
version = "0.30.0-alpha2"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to libwayland-egl."
readme = "README.md"

[dependencies]
wayland-backend = { version = "0.1.0-alpha2", path = "../wayland-backend", features = ["client_system"] }
wayland-sys = { version = "0.30.0-alpha2", path="../wayland-sys", features = ["egl"] }
