[package]
name = "wayland-server"
version = "0.6.0-alpha"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_server/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol, server side."
build = "build.rs"

[dependencies]
bitflags = "0.3.3"
crossbeam = "0.1.5"
libc = "0.2"
wayland-sys = { version = "0.6.0", features = ["server"] }

[build-dependencies]
wayland-scanner = { version = "0.6.0" }

[dev-dependencies]
byteorder = "0.3"
tempfile = "1.1"

[features]
unstable-protocols = []
wpu-xdg_shell = []
