[package]
name = "wayland-server"
version = "0.7.0-pre"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_server/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol, server side."

[dependencies]
wayland-sys = { version = "0.7.0-pre", features = ["server"], path = "../wayland-sys" }

[build-dependencies]
wayland-scanner = { version = "0.7.0-pre", path = "../wayland-scanner" }

[features]
dlopen = ["wayland-sys/dlopen"]
