[package]
name = "wayland-server"
version = "0.8.3"
documentation = "https://vberger.github.io/wayland-client-rs/wayland_server/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "server", "compositor"]
description = "Bindings to the standard C implementation of the wayland protocol, server side."
build = "build.rs"

[badges]
travis-ci = { repository = "vberger/wayland-client-rs" }

[dependencies]
wayland-sys = { version = "0.8.0", features = ["server"], path = "../wayland-sys" }
libc = "0.2"
bitflags = "0.7"

[build-dependencies]
wayland-scanner = { version = "0.8.0", path = "../wayland-scanner" }

[features]
dlopen = ["wayland-sys/dlopen"]
